nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "phpfpm"
    volumes:
      - ~/Code:/docker/code

phpfpm:
    build: ./php
    ports:
      - "9000:9000"
    links:
      - "mysql"
      - "memcached"
      - "redis"
    volumes:
      - ~/Code:/docker/code

mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ~/Docker/data:/var/lib/mysql

memcached:
    build: ./memcached
    ports:
      - "11211:11211"

redis:
    build: ./redis
    ports:
      - "6379:6379"